import Head from 'next/head'
import DayBox from '../components/day-box/DayBox'
import Header from '../components/header/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content">
        <Header />
        <h2>Let's get started</h2>
        <DayBox date={new Date()} />
        <DayBox date={new Date('2022-01-27')} isSelected={true} />
      </main>
      </>
  )
}
