import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { ChangeEventHandler, useEffect, useState } from 'react'
import { v4 as uuid } from 'uuid'
import DayList from '../components/day-list/DayList'
import Header from '../components/header/Header'
import { dateToDay } from '../lib/dates'
import styles from './index.module.css'


const allHealthGoals = [
  { value: 'brain-health', label: 'Brain Health' },
  { value: 'physical-recovery', label: 'Physical Recovery' },
  { value: 'general-wellbeing', label: 'General Wellbeing' },
  { value: 'mental-wellbeing', label: 'Mental Wellbeing' }
]

export const getServerSideProps: GetServerSideProps<Props> = async (context) => {
  let userId = context.req.cookies.userId
  if (!userId) {
    userId = uuid()
  }

  return { props: { userId } }
}

interface Props {
  userId: string
}

export const Home: React.FC<Props> = ({ userId }) => {
  const [startDate, setStartDate]= useState(dateToDay(new Date()))
  const [healthGoals, setHealthGoals] = useState<string[]>([])

  useEffect(() => {
    if (document.cookie) {
      document.cookie = `userId=${userId}; path=/;`
    }
  }, [])

  const handleHealthGoalCheck: ChangeEventHandler<HTMLInputElement> = (event) => {
    let newHealthGoals = [...healthGoals]
    if (event.target.checked) {
      newHealthGoals.push(event.target.value)
    } else {
      newHealthGoals = newHealthGoals.filter((healthGoal) => healthGoal !== event.target.value)
    }

    if (newHealthGoals.length > 2) {
      newHealthGoals = newHealthGoals.slice(1)
    }

    setHealthGoals(newHealthGoals)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content">
          <Header />
          <h2>Let's get started</h2>
          <p className={styles['day-label']}id="top">When do you want your week to start?</p>
          <DayList startDate={dateToDay(new Date())} selectedDate={startDate} onClick={setStartDate} />
          <p className={styles['health-goals-label']}>
            What health goals would you<br/>like to prioritise?
            <span>Select up to 2 goals</span>
          </p>
          <div className={styles['health-goals']}>
            <div>
              {allHealthGoals.slice(0,2).map((healthGoal) => {
                return (
                <div key={healthGoal.value} className={`${styles['checkbox-container']}`}>
                  <input
                    id={`health-goal-${healthGoal.value}`}
                    name="health-goal"
                    type="checkbox"
                    checked={healthGoals.includes(healthGoal.value)}
                    value={healthGoal.value}
                    onChange={handleHealthGoalCheck}
                    className={styles['checkbox-input']}
                  />
                  <label
                    className={`${styles['checkbox-label']} ${healthGoals.includes(healthGoal.value) ? styles['checkbox-label--selected'] : ''}`}
                    htmlFor={`health-goal-${healthGoal.value}`}
                  >
                    {healthGoal.label}
                  </label>
                </div>
                )
              })}
            </div>
            <div className={styles['checkbox-group-right']}>
              {allHealthGoals.slice(2).map((healthGoal) => {
                return (
                <div key={healthGoal.value} className={`${styles['checkbox-container']}`}>
                  <input
                    id={`health-goal-${healthGoal.value}`}
                    name="health-goal"
                    type="checkbox"
                    checked={healthGoals.includes(healthGoal.value)}
                    value={healthGoal.value}
                    onChange={handleHealthGoalCheck}
                    className={styles['checkbox-input']}
                  />
                  <label
                    className={`${styles['checkbox-label']} ${healthGoals.includes(healthGoal.value) ? styles['checkbox-label--selected'] : ''}`}
                    htmlFor={`health-goal-${healthGoal.value}`}
                  >
                    {healthGoal.label}
                  </label>
                </div>
                )
              })}
            </div>
          </div>
          <div className={styles['action-container']}>
            <button className="cta-button">Start Planning</button>
          </div>

      </main>
      </>
  )
}

export default Home